#!/bin/bash

INPUT_DIR="generated_mutants"
OUTPUT_DIR="minimized_results"
ROSETTA_BIN="$ROSETTA3/bin/minimize.static.linuxgccrelease"

mkdir -p "$OUTPUT_DIR"

# Loop through all .cif files generated by PyMOL
for cif in "$INPUT_DIR"/*.cif; do
    [ -e "$cif" ] || continue
    basename=$(basename "$cif" .cif)
    
    echo "Minimizing: $basename"
    
    $ROSETTA_BIN \
        -s "$cif" \
        -out:file:o "$OUTPUT_DIR/${basename}_min.pdb" \
        -out:path:all "$OUTPUT_DIR" \
        -overwrite
done